# Generated by Django 3.0.3 on 2020-04-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20200424_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojas',
            name='valor_frete',
            field=models.IntegerField(default=0),
        ),
    ]
