# Generated by Django 3.0.3 on 2020-04-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_lojas_valor_frete'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias_lojas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('taxa_servico', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
