# Generated by Django 3.0.3 on 2020-04-29 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_categorias_lojas'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojas',
            name='categoria',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='cadastros.categorias_lojas'),
            preserve_default=False,
        ),
    ]
