# Generated by Django 3.0.3 on 2020-05-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_lojas_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojas',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
