# Generated by Django 3.0.3 on 2020-05-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20200501_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojas',
            name='Banco',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lojas',
            name='agencia',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lojas',
            name='conta',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lojas',
            name='digito_agencia',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='lojas',
            name='digito_conta',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
