# Generated by Django 3.0.3 on 2020-05-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_auto_20200503_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lojas',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lojas',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='lojas',
            name='Telefone',
            field=models.CharField(max_length=10),
        ),
    ]
