# Generated by Django 3.0.3 on 2020-05-22 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20200508_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_abre', models.DecimalField(decimal_places=2, max_digits=4)),
                ('seg_fecha', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ter_abre', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ter_fecha', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qua_abre', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qua_fecha', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qui_abre', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qui_fecha', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sex_abre', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sex_fecha', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sab_abre', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sab_fecha', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dom_abre', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dom_fecha', models.DecimalField(decimal_places=2, max_digits=4)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Lojas')),
            ],
        ),
    ]
