# Generated by Django 3.0.6 on 2020-05-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojas',
            name='logomarca',
            field=models.ImageField(upload_to='media/logomarcas/'),
        ),
    ]
