# Generated by Django 3.0.6 on 2020-05-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_auto_20200525_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='loja',
        ),
        migrations.AddField(
            model_name='lojas',
            name='horarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastros.horarios'),
            preserve_default=False,
        ),
    ]
