# Generated by Django 3.0.6 on 2020-06-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_auto_20200530_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='problemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=15)),
                ('Mensagem', models.TextField(max_length=500)),
            ],
        ),
    ]
