# Generated by Django 3.0.4 on 2020-05-20 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20200508_0048'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto_restaurante',
            name='id_loja',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Lojas'),
            preserve_default=False,
        ),
    ]
