# Generated by Django 3.0.3 on 2020-05-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20200508_0048'),
        ('restaurantes', '0002_produto_restaurante_id_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='bebidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='produtos')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Lojas')),
            ],
        ),
    ]
