# Generated by Django 3.0.3 on 2020-05-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0010_auto_20200508_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('Banco', models.CharField(blank=True, max_length=25, null=True)),
                ('agencia', models.CharField(blank=True, max_length=8, null=True)),
                ('digito_agencia', models.CharField(blank=True, max_length=2, null=True, verbose_name='digito da agência')),
                ('conta', models.CharField(blank=True, max_length=8, null=True)),
                ('digito_conta', models.CharField(blank=True, max_length=2, null=True, verbose_name='digito da conta')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Lojas')),
            ],
        ),
    ]
