# Generated by Django 3.0.3 on 2020-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagens_produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_barras', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='produtos')),
            ],
        ),
    ]
