# Generated by Django 3.0.3 on 2020-05-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_imagens_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens_produtos',
            name='nome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
