# Generated by Django 3.0.3 on 2020-05-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_imagens_produtos_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='produto_pesavel',
            field=models.CharField(default='não', max_length=5, verbose_name='Produto vendido por peso?'),
        ),
    ]
