# Generated by Django 3.0.3 on 2020-05-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produtos_produto_pesavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, default='#', null=True, upload_to='produtos'),
        ),
    ]
