# Generated by Django 3.0.3 on 2020-04-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20200424_2219'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='loja',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Lojas'),
            preserve_default=False,
        ),
    ]
