# Generated by Django 3.0.3 on 2020-04-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedidos_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='forma_de_pagamento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
