# Generated by Django 3.0.3 on 2020-04-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedidos_forma_de_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='CEP',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='Cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='Estado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='Rua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='complemento',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
