# Generated by Django 3.0.3 on 2020-04-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20200429_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='troco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='valor_troco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
