# Generated by Django 3.0.3 on 2020-04-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedidos_valor_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='taxa_servico',
            field=models.IntegerField(default=0),
        ),
    ]
