# Generated by Django 3.0.3 on 2020-05-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedidos_taxa_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
