# Generated by Django 3.0.3 on 2020-05-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20200430_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='taxa_servico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
