# Generated by Django 3.0.3 on 2020-05-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_auto_20200501_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='pedido_cancelado',
            field=models.CharField(default='não', max_length=5),
        ),
    ]
