# Generated by Django 3.0.3 on 2020-05-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedidos_pedido_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='motivo_cancelamento',
            field=models.TextField(default='não cancelado', max_length=300),
        ),
    ]
