# Generated by Django 3.0.3 on 2020-05-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pedidos_motivo_cancelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='motivo_cancelamento',
            field=models.TextField(default='', max_length=300),
        ),
    ]
