# Generated by Django 3.0.3 on 2020-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_auto_20200503_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status_entrega',
            field=models.CharField(default='não entregue', max_length=15),
        ),
    ]
