# Generated by Django 3.0.3 on 2020-05-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_auto_20200506_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
