# Generated by Django 3.0.6 on 2020-05-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_pedidos_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='observacao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observação'),
        ),
    ]
