# Generated by Django 3.0.3 on 2020-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenadas', '0002_auto_20200429_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cep',
            name='Cidade',
        ),
        migrations.RemoveField(
            model_name='cep',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='cep',
            name='Rua',
        ),
        migrations.RemoveField(
            model_name='cep',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='cep',
            name='numero',
        ),
        migrations.AddField(
            model_name='cep',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
